sonar.projectKey=pensilpos-ticket-backend
sonar.projectName=Pensilpos Ticket Backend
sonar.host.url=http://localhost:10000

sonar.sources=src,node-service.js
sonar.tests=tests,tests-integration
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-integration/lcov.info
sonar.coverage.exclusions=src/app.js,node-service.js
